{
  config,
  lib,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.text-editors-cli;
  notExcluded = pkg: !(builtins.elem pkg config.text-editors-cli.excludePackages);
in
{
  options = {
    text-editors-cli = {
      enable = mkEnableOption "Enables all all cli text-editors";

      excludePackages = mkOption {
        description = "List of text-editors-cli packages to exclude from the default home";
        type = types.listOf types.package;
        default = [ ];
      };
    };
  };

  config = mkIf cfg.enable {
    home.packages = subtractLists cfg.excludePackages (with pkgs; [ amp ]);

    programs = {
      helix = {
        enable = notExcluded pkgs.helix;
        defaultEditor = notExcluded pkgs.helix && !config.programs.nixvim.defaultEditor;
        settings = importTOML ./helix-vim.toml;
      };

      nixvim = {
        enable = notExcluded pkgs.neovim;
        defaultEditor = notExcluded pkgs.neovim;

        enableMan = false;

        extraConfigLuaPre = '''';

        extraConfigLua = ''
          require('render-markdown').setup({})
        '';

        extraConfigLuaPost = '''';

        # Not list of packages, FIXIT!
        #extraLuaPackages = with pkgs; [
        #];

        extraPackages = with pkgs; [ ];

        extraPython3Packages = p: with p; [ ];

        globalOpts = {
          #vim.opt_global.*
        };

        globals = {
          #vim.g.*
          mapleader = " ";
        };

        localOpts = {
          #vim.opt_local.*
        };

        opts = {
          #vim.opt.*
          number = true;
          relativenumber = true;
          expandtab = true;
          tabstop = 2;
          shiftwidth = 2;
          timeout = true;
          timeoutlen = 200;
        };

        #viAlias = true;
        #vimAlias = true;
        #withNodeJs = true;

        keymaps = [
          {
            mode = "n";
            key = "<leader>t";
            action = ":NvimTreeToggle<CR>";
            options = {
              silent = true;
              noremap = true;
              desc = "Toggle nvim-tree";
            };
          }
          {
            mode = "n";
            key = "<leader>r";
            action = ":RenderMarkdownToggle<CR>";
            options = {
              silent = true;
              noremap = true;
              desc = "Toggle render-markdown";
            };
          }
        ];

        extraPlugins = with pkgs.vimPlugins; [ render-markdown ];

        clipboard.providers.wl-copy = {
          enable = true;
          package = pkgs.wl-clipboard-rs;
        };

        colorschemes.catppuccin = {
          enable = true;
          settings = {
            flavor = "${config.catppuccin.flavor}";
            #transparentBackground = true;
            background = {
              dark = "${config.catppuccin.flavor}";
              light = "${config.catppuccin.flavor}";
            };
            dim_inactive = {
              enabled = true;
              #percentage = 0.15;
            };
          };
        };

        plugins = {
          cmp = {
            enable = true;
          };

          dashboard = {
            enable = true;
            settings = {
              theme = "doom";
              config = {
                # Generated by https://emojicombos.com
                header = [
                  ""
                  "⢠⢦⣓⢮⡿⣝⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣟⣯⢿⣽⢻⢾⣽⣣"
                  "⣫⣟⡼⣻⣿⡽⣿⣿⣟⣿⣽⣷⣿⣿⣿⣿⣿⣿⢾⣿⣿⣿⡽⣷⣿⣿⣿⣽⣿⣷⣿⣿⣿⡿⣿⣿⣿⣿⣿⣟⡷⣟⣿⣞⡿⣞⣿⣻⣞⣷"
                  "⣳⣯⢿⣽⣿⢿⣿⣿⣿⣸⣿⢽⣿⣿⣿⣽⣿⣿⣿⣻⣿⣯⣿⢿⣿⣿⣷⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⢾⣻⣿⣟⣿⣻⢿⣻⣽⣞⡷⣯⢿"
                  "⣿⣿⢯⣿⣿⣿⣿⣿⡟⠀⣿⠀⠹⣿⣿⡷⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⡇⢻⣿⣿⣿⣿⣿⣿⣿⡿⣿⣯⣿⣻⠘⣿⣳⣯⢿⣻⣿"
                  "⣿⣿⡿⣿⣿⣻⡟⣿⣷⡀⢹⣀⣀⠙⢿⣇⠈⣿⢿⣿⣿⣿⣿⣾⣿⣿⣿⣿⡿⠉⢩⣛⣿⣿⣿⣿⣿⣷⣿⣿⣿⣳⡿⠀⣿⣟⣾⡿⣯⣿"
                  "⣿⣿⣿⣿⣿⣿⡇⠸⣧⣽⣶⣷⣧⣤⣭⣛⡦⢽⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⠀⠀⠘⠿⠛⠙⢿⣿⣿⣿⣿⣿⣿⣿⡇⠀⣿⣾⣻⣽⣿⣿"
                  "⣿⣿⣿⣿⣿⣿⠧⢿⡿⠛⠛⠟⠻⣿⣿⣿⣿⡻⣿⣽⣿⣿⣿⣿⣿⣿⠸⣿⣀⡀⠤⠀⠤⡤⠀⡙⣿⣿⣿⣿⡿⡽⠈⢱⣿⣟⣿⣿⣿⣿"
                  "⣿⣿⣟⣿⣽⣿⠂⣿⠀⠀⢠⣤⣤⣼⣿⣿⡿⢍⢻⣟⣿⣿⣿⡟⣿⣿⠀⢹⡇⠀⠤⣤⣤⣽⣦⣄⣀⡉⠻⣿⣿⠃⠀⢸⣿⣿⣿⣿⣿⣿"
                  "⣼⣿⣟⢿⣯⢿⠀⢻⡀⠀⢸⣿⣿⣿⣿⣿⡇⠀⠈⢯⣟⣿⣯⡇⠹⣿⡄⠀⣳⣴⡿⠿⠛⠛⠻⢿⣿⣿⣿⣿⣯⣄⣠⣿⣿⣿⣿⣿⣿⣿"
                  "⣿⢿⡺⣿⣿⣽⡀⠀⠁⠀⢸⡏⢷⣛⡿⢿⠁⠀⠀⠈⢺⡽⣞⡇⠀⠘⢷⡀⠀⠀⠀⠀⠀⠀⠀⣄⠀⢙⣿⣿⣿⣿⣿⣿⣿⣿⠟⣹⠟⣿"
                  "⠁⢘⡷⣿⣿⣷⡇⠀⠀⠲⢬⣿⣄⣉⡠⠂⠀⠀⠀⠀⠀⠙⢽⣷⢠⠀⠀⠓⠀⠀⠀⠀⠀⠀⢸⣿⡿⣿⣿⣿⣿⣿⣿⡿⠿⣷⡽⠋⣸⣿"
                  "⠀⡬⣳⣿⣿⡏⠳⠀⠀⠀⠀⠀⠀⠀⡀⢔⡖⠀⠀⠀⠀⠀⠀⠙⠜⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⣷⠹⣿⡿⢋⣿⡿⠁⢠⣿⠟⣾⣿⣿"
                  "⠀⢲⣽⣿⣿⡇⠀⠑⠀⠀⠀⠀⠀⠰⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⢧⡘⠷⢶⠄⣫⠞⠀⣠⡿⢃⣾⢿⡻⢜"
                  "⠀⢳⢾⣿⣯⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠓⠒⠙⠛⠛⡭⡄⠄⠴⠛⢚⡟⠏⣣⣵⣿"
                  "⠀⢭⣿⣿⣻⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⢔⣣⣴⣾⣿⣿⣿"
                  "⢘⢲⣿⢯⡟⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠤⣤⣶⣭⣾⣿⣿⣿⣿⣿⣿⣿"
                  "⠸⣸⡟⣾⡇⠀⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠠⠴⠿⣟⡿⣿⣿⣿⣿"
                  "⠀⣿⡑⣯⠇⠀⠐⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣙⢾⣟⡷⣿⣿"
                  "⠠⢇⠘⣿⠀⠀⠀⢱⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡞⣬⡿⣞⣿⣿⣿"
                  "⠐⠌⠐⡿⠀⠀⠀⢸⣳⡀⠀⠀⠀⠀⠀⠀⠀⠺⠽⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⢑⣾⡝⣯⣿⣿⣽"
                  "⠠⠈⠀⣏⠀⠀⠀⣸⢷⡿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡎⣼⠧⣟⣾⣿⣟⣿"
                  "⠀⠀⠀⡃⠀⠀⠀⣏⠟⡿⣽⠑⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⢴⢣⡟⣞⣽⣿⣟⣯⣿"
                  "⠀⠀⠀⡥⠀⠀⠀⣯⢶⡽⡹⠀⠈⠢⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣤⡶⠓⠈⣏⡟⣜⣾⣿⣯⠺⣽⣿"
                  "⠀⠀⠀⣱⠀⠀⠀⣟⣾⡝⡇⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣤⣴⣶⣿⠿⠛⠁⠀⠀⣼⠟⣘⣾⣿⣳⣯⢿⣾⣿"
                  "⠀⠀⠀⢸⠀⠀⠀⠙⣺⢍⡇⠀⠀⠀⠀⠀⠁⠠⠀⠀⠀⠤⠤⠀⠐⠒⠀⠉⢿⣿⣿⣿⠟⠋⠁⠀⠀⠀⠀⣰⡏⣬⣿⣿⡟⣷⣯⣿⣿⡿"
                  ""
                ];
                #footer = [
                #  ""
                #  "⡿⠋⠄⣀⣀⣤⣴⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣌⠻⣿⣿"
                #  "⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠹⣿"
                #  "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠹"
                #  "⣿⣿⡟⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡛⢿⣿⣿⣿⣮⠛⣿⣿⣿⣿⣿⣿⡆"
                #  "⡟⢻⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣣⠄⡀⢬⣭⣻⣷⡌⢿⣿⣿⣿⣿⣿"
                #  "⠃⣸⡀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠈⣆⢹⣿⣿⣿⡈⢿⣿⣿⣿⣿"
                #  "⠄⢻⡇⠄⢛⣛⣻⣿⣿⣿⣿⣿⣿⣿⣿⡆⠹⣿⣆⠸⣆⠙⠛⠛⠃⠘⣿⣿⣿⣿"
                #  "⠄⠸⣡⠄⡈⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⠁⣠⣉⣤⣴⣿⣿⠿⠿⠿⡇⢸⣿⣿⣿"
                #  "⠄⡄⢿⣆⠰⡘⢿⣿⠿⢛⣉⣥⣴⣶⣿⣿⣿⣿⣻⠟⣉⣤⣶⣶⣾⣿⡄⣿⡿⢸"
                #  "⠄⢰⠸⣿⠄⢳⣠⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣼⣿⣿⣿⣿⣿⣿⡇⢻⡇⢸"
                #  "⢷⡈⢣⣡⣶⠿⠟⠛⠓⣚⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⢸⠇⠘"
                #  "⡀⣌⠄⠻⣧⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠛⠛⠛⢿⣿⣿⣿⣿⣿⡟⠘⠄⠄"
                #  "⣷⡘⣷⡀⠘⣿⣿⣿⣿⣿⣿⣿⣿⡋⢀⣠⣤⣶⣶⣾⡆⣿⣿⣿⠟⠁⠄⠄⠄⠄"
                #  "⣿⣷⡘⣿⡀⢻⣿⣿⣿⣿⣿⣿⣿⣧⠸⣿⣿⣿⣿⣿⣷⡿⠟⠉⠄⠄⠄⠄⡄⢀"
                #  "⣿⣿⣷⡈⢷⡀⠙⠛⠻⠿⠿⠿⠿⠿⠷⠾⠿⠟⣛⣋⣥⣶⣄⠄⢀⣄⠹⣦⢹⣿"
                #  ""
                #];
                center = [
                  {
                    action = "SessionLoad";
                    desc = "Reload Last Session";
                    icon = " ";
                    key = "a";
                    keymap = "SPC q l";
                    key_format = "";
                  }
                  {
                    action = "Telescope oldfiles";
                    desc = "Recently Opened Files";
                    icon = " ";
                    key = "b";
                    keymap = "SPC f r";
                    key_format = "";
                  }
                  {
                    action = "Telescope marks";
                    desc = "Open Project";
                    icon = " ";
                    key = "c";
                    keymap = "SPC f p";
                    key_format = "";
                  }
                  {
                    action = "Telescope project";
                    desc = "Jump to Bookmark";
                    icon = " ";
                    key = "d";
                    keymap = "SPC f b";
                    key_format = "";
                  }
                  {
                    action = "Telescope find_files";
                    desc = "Find File";
                    icon = " ";
                    key = "e";
                    keymap = "SPC f f";
                    key_format = "";
                  }
                  {
                    action = "Telescope live_grep";
                    desc = "Find Word";
                    icon = " ";
                    key = "f";
                    keymap = "SPC s p";
                    key_format = "";
                  }
                  {
                    action = ":e ~/nix/modules/home-manager/text-editors-cli/default.nix";
                    desc = "Open Neovim Configuration";
                    icon = " ";
                    key = "g";
                    keymap = "SPC f p";
                    key_format = "";
                  }
                ];
              };
            };
          };

          lsp = {
            enable = true;
            servers = {
              bashls = {
                enable = true;
              };
              lua-ls = {
                enable = true;
              };
              nil-ls = {
                enable = true;
              };
              nushell = {
                enable = true;
              };
              ruff-lsp = {
                enable = true;
              };
              typos-lsp = {
                enable = true;
              };
            };
          };

          lsp-lines = {
            enable = true;
          };

          #lspsaga = {
          #  enable = true;
          #};

          lualine = {
            enable = true;
            componentSeparators.left = "";
            componentSeparators.right = "";
            sectionSeparators.left = "";
            sectionSeparators.right = "";
          };

          nvim-colorizer = {
            enable = true;
          };

          nvim-surround = {
            enable = true;
          };

          nvim-tree = {
            enable = true;
          };

          sniprun = {
            enable = true;
          };

          telescope = {
            enable = true;
          };

          treesitter = {
            enable = true;
          };

          which-key = {
            enable = true;
          };
        };
      };
    };
  };
}
